// Report 50375 "Order Confirmation2 test"
// {
//     Caption = 'Order Confirmation';
//     PreviewMode = Normal;
//     RDLCLayout = './Layouts/OrderConfirmation2test.rdlc';
//     DefaultLayout = RDLC;

//     dataset
//     {
//         dataitem("Sales Header"; "Sales Header")
//         {
//             DataItemTableView = sorting("Document Type", "No.") where("Document Type" = const(Order));
//             RequestFilterFields = "No.", "Sell-to Customer No.", "No. Printed";
//             RequestFilterHeading = 'Sales Order';
//             column(ExtendedInformation; ExtendedInformation)
//             {
//             }
//             column(ExtensdedeInformation; ExtensdedeInformation)
//             {
//             }
//             column(No_SalesHeader_1; "Sales Header"."No.")
//             {
//             }
//             column(PostingDate_SalesHeader1; "Sales Header"."Posting Date")
//             {
//             }
//             column(CompanyInfo_PANNo1; CompanyInfo."P.A.N. No.")
//             {
//             }
//             column(contect_person; Cust.Contact)
//             {
//             }
//             column(contectmailid; Cust."E-Mail")
//             {
//             }
//             column(ContactPhn; Cust."Phone No.")
//             {
//             }
//             column(PRint_Terms; PRint_Terms)
//             {
//             }
//             column(SBCessPerc; 'SBCess @' + Format(SBCessPerc) + '%')
//             {
//             }
//             column(SBCess; SBCess)
//             {
//             }
//             column(SbCessAmt; SbCessAmt)
//             {
//             }
//             column(Pdate; "Sales Header"."Posting Date")
//             {
//             }
//             column(kkCAmt; kkCAmt)
//             {
//             }
//             column(KKCessPerc; 'KKCess @0.5%')
//             {
//             }
//             column(ServiceTaxAmount; ServiceTaxAmount)
//             {
//             }
//             column(DocumentType_SalesHeader; "Sales Header"."Document Type")
//             {
//             }
//             column(No_SalesHeader; "Sales Header"."No.")
//             {
//             }
//             column(InvDiscAmtCaption; InvDiscAmtCaptionLbl)
//             {
//             }
//             column(ShowTerms; ShowTerms)
//             {
//             }
//             column(VATPercentCaption; VATPercentCaptionLbl)
//             {
//             }
//             column(VATBaseCaption; VATBaseCaptionLbl)
//             {
//             }
//             column(VATAmtCaption; VATAmtCaptionLbl)
//             {
//             }
//             column(LineAmtCaption; LineAmtCaptionLbl)
//             {
//             }
//             column(VATIdentCaption; VATIdentCaptionLbl)
//             {
//             }
//             column(TotalCaption; TotalCaptionLbl)
//             {
//             }
//             column(LocationServiceTax; LocationServiceTax)
//             {
//             }
//             column(locationTIN; locationTIN)
//             {
//             }
//             column(Prod1; Prod[1])
//             {
//             }
//             column(Prod2; Prod[2])
//             {
//             }
//             column(Prod3; Prod[3])
//             {
//             }
//             column(Prod4; Prod[4])
//             {
//             }
//             column(Prod5; Prod[5])
//             {
//             }
//             column(SelltoAddress_SalesHeader; "Sales Header"."Sell-to Address")
//             {
//             }
//             column(Prod6; Prod[6])
//             {
//             }
//             column(Prod7; Prod[7])
//             {
//             }
//             column(Prod8; Prod[8])
//             {
//             }
//             column(Prod9; Prod[9])
//             {
//             }
//             column(Prod10; Prod[10])
//             {
//             }
//             column(Terms1; Terrms1)
//             {
//             }
//             column(Terms2; Terrms2)
//             {
//             }
//             column(Terms3; Terrms3)
//             {
//             }
//             column(Terms4; Terrms4)
//             {
//             }
//             column(Terms5; Terrms5)
//             {
//             }
//             column(ProductBoolean; ProductBoolean)
//             {
//             }
//             dataitem(CopyLoop; Integer)
//             {
//                 DataItemTableView = sorting(Number);
//                 column(ReportForNavId_5701; 5701) { } // Autogenerated by ForNav - Do not delete
//                 dataitem(PageLoop; Integer)
//                 {
//                     DataItemTableView = sorting(Number) where(Number = const(1));
//                     column(city; "Sales Header"."Bill-to City")
//                     {
//                     }
//                     column(ContaCt; "Sales Header"."Sell-to Contact")
//                     {
//                     }
//                     column(CompanyInfo2Picture; CompanyInfo2.Picture)
//                     {
//                     }
//                     column(CompanyInfo1Picture; CompanyInfo1.Picture)
//                     {
//                     }
//                     column(CompanyInfo3Picture; CompanyInfo3.Picture)
//                     {
//                     }
//                     column(Logo_Ax; CompanyInfo."Logo AX")
//                     {
//                     }
//                     column(Logo_Nav; CompanyInfo."Logo NAV")
//                     {
//                     }
//                     column(DocumentCaptionCopyText; StrSubstNo(Text004, CopyText))
//                     {
//                     }
//                     column(CustAddr1; CustAddr[1])
//                     {
//                     }
//                     column(CompanyAddr1; CompanyAddr[1])
//                     {
//                     }
//                     column(CustAddr2; CustAddr[2])
//                     {
//                     }
//                     column(CompanyAddr2; CompanyAddr[2])
//                     {
//                     }
//                     column(CustAddr3; CustAddr[3])
//                     {
//                     }
//                     column(CompanyAddr3; CompanyAddr[3])
//                     {
//                     }
//                     column(CustAddr4; CustAddr[4])
//                     {
//                     }
//                     column(CompanyAddr4; CompanyAddr[4])
//                     {
//                     }
//                     column(CustAddr5; CustAddr[5])
//                     {
//                     }
//                     column(CompanyInfoPhoneNo; CompanyInfo."Phone No.")
//                     {
//                     }
//                     column(CustAddr6; CustAddr[6])
//                     {
//                     }
//                     column(PaymentTermsDescription; PaymentTerms.Description)
//                     {
//                     }
//                     column(ShipmentMethodDescription; ShipmentMethod.Description)
//                     {
//                     }
//                     column(PrepmtPaymentTermsDescription; PrepmtPaymentTerms.Description)
//                     {
//                     }
//                     column(CompanyInfoEMail; CompanyInfo."E-Mail")
//                     {
//                     }
//                     column(CompanyInfoHomePage; CompanyInfo."Home Page")
//                     {
//                     }
//                     column(CompanyInfoVATRegNo; CompanyInfo."GST Registration No.")
//                     {
//                     }
//                     column(CompanyInfoGiroNo; CompanyInfo."Giro No.")
//                     {
//                     }
//                     column(CompanyInfoBankName; CompanyInfo."Bank Name")
//                     {
//                     }
//                     column(CompanyInfoBankAccountNo; "Sales Header"."External Document No.")
//                     {
//                     }
//                     column(BillToCustNo_SalesHeader; "Sales Header"."Bill-to Customer No.")
//                     {
//                         IncludeCaption = false;
//                     }
//                     column(DocumentDate_SalesHeader; Format("Sales Header"."Document Date", 0, 4))
//                     {
//                     }
//                     column(VATNoText; VATNoText)
//                     {
//                     }
//                     column(VATRegNo_SalesHeader; BilltoGSTRegNo)
//                     {
//                     }
//                     column(ShipmentDate_SalesHeader; Format("Sales Header"."Shipment Date"))
//                     {
//                     }
//                     column(SalesPersonText; SalesPersonText)
//                     {
//                     }
//                     column(SalesPurchPersonName; SalesPurchPerson.Name)
//                     {
//                     }
//                     column(ReferenceText; ReferenceText)
//                     {
//                     }
//                     column(YourReference_SalesHeader; "Sales Header"."Your Reference")
//                     {
//                     }
//                     column(CustAddr7; CustAddr[7])
//                     {
//                     }
//                     column(CustAddr8; CustAddr[8])
//                     {
//                     }
//                     column(CompanyAddr5; CompanyAddr[5])
//                     {
//                     }
//                     column(CompanyAddr6; CompanyAddr[6])
//                     {
//                     }
//                     column(PricesInclVAT_SalesHeader; "Sales Header"."Prices Including VAT")
//                     {
//                         IncludeCaption = false;
//                     }
//                     column(PageCaption; StrSubstNo(Text005, ''))
//                     {
//                     }
//                     column(OutputNo; OutputNo)
//                     {
//                     }
//                     column(PricesInclVATYesNo; Format("Sales Header"."Prices Including VAT"))
//                     {
//                     }
//                     column(PhoneNoCaption; PhoneNoCaptionLbl)
//                     {
//                     }
//                     column(BillToCustNo_SalesHeaderCaption; "Sales Header".FieldCaption("Bill-to Customer No."))
//                     {
//                     }
//                     column(PricesInclVAT_SalesHeaderCaption; "Sales Header".FieldCaption("Prices Including VAT"))
//                     {
//                     }
//                     column(HomePageCaption; HomePageCaptionLbl)
//                     {
//                     }
//                     column(VATRegNoCaption; VATRegNoCaptionLbl)
//                     {
//                     }
//                     column(GiroNoCaption; GiroNoCaptionLbl)
//                     {
//                     }
//                     column(BankNameCaption; BankNameCaptionLbl)
//                     {
//                     }
//                     column(BankAccNoCaption; BankAccNoCaptionLbl)
//                     {
//                     }
//                     column(ShpDateCaption; ShpDateCaptionLbl)
//                     {
//                     }
//                     column(OrderNoCaption; OrderNoCaptionLbl)
//                     {
//                     }
//                     column(EMailCaption; EMailCaptionLbl)
//                     {
//                     }
//                     column(PmtTermsDescCaption; PmtTermsDescCaptionLbl)
//                     {
//                     }
//                     column(ShipMethodDescCaption; ShipMethodDescCaptionLbl)
//                     {
//                     }
//                     column(PrepmtTermsDescCaption; PrepmtTermsDescCaptionLbl)
//                     {
//                     }
//                     column(DocDateCaption; DocDateCaptionLbl)
//                     {
//                     }
//                     column(AmtCaption; AmtCaptionLbl)
//                     {
//                     }
//                     dataitem(DimensionLoop1; Integer)
//                     {
//                         DataItemLinkReference = "Sales Header";
//                         DataItemTableView = sorting(Number) where(Number = filter(1 ..));
//                         column(DimText; DimText)
//                         {
//                         }
//                         column(Number_Integer; DimensionLoop1.Number)
//                         {
//                         }
//                         column(HdrDimsCaption; HdrDimsCaptionLbl)
//                         {
//                         }
//                         trigger OnPreDataItem();
//                         begin
//                             if not ShowInternalInfo then
//                                 CurrReport.Break;
//                         end;

//                         trigger OnAfterGetRecord();
//                         begin
//                             if Number = 1 then begin
//                                 if not DimSetEntry1.Find('-') then
//                                     CurrReport.Break;
//                             end else
//                                 if not Continue then
//                                     CurrReport.Break;
//                             Clear(DimText);
//                             Continue := false;
//                             repeat
//                                 OldDimText := DimText;
//                                 if DimText = '' then
//                                     DimText := StrSubstNo(
//                                       '%1 %2', DimSetEntry1."Dimension Code", DimSetEntry1."Dimension Value Code")
//                                 else
//                                     DimText :=
//                                       StrSubstNo(
//                                         '%1, %2 %3', DimText,
//                                         DimSetEntry1."Dimension Code", DimSetEntry1."Dimension Value Code");
//                                 if StrLen(DimText) > MaxStrLen(OldDimText) then begin
//                                     DimText := OldDimText;
//                                     Continue := true;
//                                     exit;
//                                 end;
//                             until (DimSetEntry1.Next = 0);
//                         end;

//                     }
//                     dataitem("Sales Line"; "Sales Line")
//                     {
//                         DataItemLink = "Document Type" = field("Document Type"), "Document No." = field("No.");
//                         DataItemLinkReference = "Sales Header";
//                         DataItemTableView = sorting("Document Type", "Document No.", "Line No.");
//                         trigger OnPreDataItem();
//                         begin
//                             CurrReport.Break;
//                         end;

//                     }
//                     dataitem(RoundLoop; Integer)
//                     {
//                         DataItemTableView = sorting(Number);
//                         column(No_Int; No_Int)
//                         {
//                         }
//                         column(Comment_text; Comment_text[1])
//                         {
//                         }
//                         column(SalesLineLineAmount; SalesLine."Line Amount")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(Description_SalesLine; "Sales Line".Description)
//                         {
//                             IncludeCaption = false;
//                         }
//                         column(NNCSalesLineLineAmt; NNC_SalesLineLineAmt)
//                         {
//                         }
//                         column(NNCSalesLineInvDiscAmt; NNC_SalesLineInvDiscAmt)
//                         {
//                         }
//                         column(NNCTotalLCY; NNC_TotalLCY)
//                         {
//                         }
//                         column(NNCVATAmt; NNC_VATAmt)
//                         {
//                         }
//                         column(NNCPmtDiscOnVAT; NNC_PmtDiscOnVAT)
//                         {
//                         }
//                         column(NNCTotalInclVAT2; NNC_TotalInclVAT2)
//                         {
//                         }
//                         column(NNCVatAmt2; NNC_VatAmt2)
//                         {
//                         }
//                         column(NNCTotalExclVAT2; NNC_TotalExclVAT2)
//                         {
//                         }
//                         column(VATBaseDisc_SalesHeader; "Sales Header"."VAT Base Discount %")
//                         {
//                         }
//                         column(ShowInternalInfo; ShowInternalInfo)
//                         {
//                         }
//                         column(SalesLine_Type; "Sales Line".Type)
//                         {
//                         }
//                         column(No_SalesLine; "Sales Line"."No.")
//                         {
//                             IncludeCaption = false;
//                         }
//                         column(Quantity_SalesLine; "Sales Line".Quantity)
//                         {
//                             IncludeCaption = false;
//                         }
//                         column(UnitofMeasure_SalesLine; "Sales Line"."Unit of Measure Code")
//                         {
//                         }
//                         column(UnitPrice_SalesLine; "Sales Line"."Unit Price")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 2;
//                         }
//                         column(LineDiscount_SalesLine; "Sales Line"."Line Discount %")
//                         {
//                         }
//                         column(SalesLineLineAmount1; "Sales Line"."Line Amount")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(AllowInvDisc_SalesLine; "Sales Line"."Allow Invoice Disc.")
//                         {
//                             IncludeCaption = false;
//                         }
//                         column(LineDiscount_SalesLineAmount; "Sales Line"."Line Discount Amount")
//                         {
//                         }
//                         column(Type_SalesLine; Format("Sales Line".Type))
//                         {
//                         }
//                         column(No_SalesLine1; "Sales Line"."Line No.")
//                         {
//                         }
//                         column(AllowInvoiceDisYesNo; Format("Sales Line"."Allow Invoice Disc."))
//                         {
//                         }
//                         column(SalesLineInvDiscAmount; -VATAmountLine."Invoice Discount Amount")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(TotalText; TotalText)
//                         {
//                         }
//                         column(SalesLineLineAmtInvDiscAmt; SalesLine."Line Amount" - VATAmountLine."Invoice Discount Amount")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(SalesLineTaxAmount; SalesLine."Tax Amount")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(ChargesAmount; ChargesAmount)
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(OtherTaxesAmount; OtherTaxesAmount)
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(TotalInclVATText; TotalInclVATText)
//                         {
//                         }
//                         column(VATAmount; SalesLine."Service Tax SHE Cess Amount")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(NNCSalesLineExciseAmt; NNC_SalesLineExciseAmt)
//                         {
//                         }
//                         column(NNCSalesLineTaxAmt; NNC_SalesLineTaxAmt)
//                         {
//                         }
//                         column(NNCSalesLineSvcTaxAmt; NNC_SalesLineSvcTaxAmt)
//                         {
//                         }
//                         column(NNCSalesLineSvcTaxeCessAmt; NNC_SalesLineSvcTaxeCessAmt)
//                         {
//                         }
//                         column(NNCSalesLineSvcSHECessAmt; NNC_SalesLineSvcSHECessAmt)
//                         {
//                         }
//                         column(NNCSalesLineTDSTCSSHECESS; NNC_SalesLineTDSTCSSHECESS)
//                         {
//                         }
//                         column(VATDiscountAmount; -VATDiscountAmount)
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(TotalExclVATText; TotalExclVATText)
//                         {
//                         }
//                         column(VATBaseAmount; VATBaseAmount)
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(VATAmtLineVATAmtText; VATAmountLine.VATAmountText)
//                         {
//                         }
//                         column(VATAmount1; VATAmount)
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(TotalAmountInclVAT; TotalAmountInclVAT)
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(No_SalesLineCaption; "Sales Line".FieldCaption("No."))
//                         {
//                         }
//                         column(Description_SalesLineCaption; "Sales Line".FieldCaption(Description))
//                         {
//                         }
//                         column(Quantity_SalesLineCaption; "Sales Line".FieldCaption(Quantity))
//                         {
//                         }
//                         column(UnitofMeasure_SalesLineCaption; "Sales Line".FieldCaption("Unit of Measure"))
//                         {
//                         }
//                         column(AllowInvDisc_SalesLineCaption; "Sales Line".FieldCaption("Allow Invoice Disc."))
//                         {
//                         }
//                         column(UnitPriceCaption; UnitPriceCaptionLbl)
//                         {
//                         }
//                         column(DiscPercentCaption; DiscPercentCaptionLbl)
//                         {
//                         }
//                         column(LineDiscCaption; LineDiscCaptionLbl)
//                         {
//                         }
//                         column(SubtotalCaption; SubtotalCaptionLbl)
//                         {
//                         }
//                         column(ExciseAmtCaption; ExciseAmtCaptionLbl)
//                         {
//                         }
//                         column(TaxAmtCaption; TaxAmtCaptionLbl)
//                         {
//                         }
//                         column(ServTaxAmtCaption; ServTaxAmtCaptionLbl)
//                         {
//                         }
//                         column(ChargesAmtCaption; ChargesAmtCaptionLbl)
//                         {
//                         }
//                         column(OtherTaxesAmtCaption; OtherTaxesAmtCaptionLbl)
//                         {
//                         }
//                         column(ServTaxeCessAmtCaption; ServTaxeCessAmtCaptionLbl)
//                         {
//                         }
//                         column(TCSAmtCaption; TCSAmtCaptionLbl)
//                         {
//                         }
//                         column(ServTaxSHECessAmtCaption; ServTaxSHECessAmtCaptionLbl)
//                         {
//                         }
//                         column(Serials; Serials)
//                         {
//                         }
//                         column(VATDisctAmtCaption; VATDisctAmtCaptionLbl)
//                         {
//                         }
//                         column(HSNCode; "Sales Line"."HSN/SAC Code")
//                         {
//                         }
//                         column(CGSTAmt; CGSTAmt)
//                         {
//                         }
//                         column(SGSTAmt; SGSTAmt)
//                         {
//                         }
//                         column(IGSTAmt; IGSTAmt)
//                         {
//                         }
//                         column(CGSTRate; CGSTRate)
//                         {
//                         }
//                         column(SGSTRate; SGSTRate)
//                         {
//                         }
//                         column(IGSTRate; IGSTRate)
//                         {
//                         }
//                         column(TotalAmount; TotalAmount)
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(AmtToCust; "Sales Line"."Amount To Customer")
//                         {
//                         }
//                         dataitem(DimensionLoop2; Integer)
//                         {
//                             DataItemTableView = sorting(Number) where(Number = filter(1 ..));
//                             column(DimText1; DimText)
//                             {
//                             }
//                             column(LineDimsCaption; LineDimsCaptionLbl)
//                             {
//                             }
//                             column(NNCSalesLineLineAmt2; NNC_SalesLineLineAmt)
//                             {
//                             }
//                             column(NNCSalesLineInvDiscAmt2; NNC_SalesLineInvDiscAmt)
//                             {
//                             }
//                             column(ChargesAmount2; ChargesAmount)
//                             {
//                             }
//                             column(OtherTaxesAmount2; OtherTaxesAmount)
//                             {
//                             }
//                             column(NNCSalesLineExciseAmt2; NNC_SalesLineExciseAmt)
//                             {
//                             }
//                             column(NNCSalesLineTaxAmt2; NNC_SalesLineTaxAmt)
//                             {
//                             }
//                             column(NNCSalesLineSvcTaxAmt2; NNC_SalesLineSvcTaxAmt)
//                             {
//                             }
//                             column(NNCSalesLineSvcTaxeCessAmt2; NNC_SalesLineSvcTaxeCessAmt)
//                             {
//                             }
//                             column(NNCSalesLineSvcSHECessAmt2; NNC_SalesLineSvcSHECessAmt)
//                             {
//                             }
//                             column(NNCSalesLineTDSTCSSHECESS2; NNC_SalesLineTDSTCSSHECESS)
//                             {
//                             }
//                             column(TotalAmount2; TotalAmount)
//                             {
//                             }
//                             trigger OnPreDataItem();
//                             begin
//                                 if not ShowInternalInfo then
//                                     CurrReport.Break;
//                                 DimSetEntry2.SetRange("Dimension Set ID", "Sales Line"."Dimension Set ID");
//                             end;

//                             trigger OnAfterGetRecord();
//                             begin
//                                 if Number = 1 then begin
//                                     if not DimSetEntry2.FindFirst then
//                                         CurrReport.Break;
//                                 end else
//                                     if not Continue then
//                                         CurrReport.Break;
//                                 Clear(DimText);
//                                 Continue := false;
//                                 repeat
//                                     OldDimText := DimText;
//                                     if DimText = '' then
//                                         DimText := StrSubstNo(
//                                           '%1 %2', DimSetEntry2."Dimension Code", DimSetEntry2."Dimension Value Code")
//                                     else
//                                         DimText :=
//                                           StrSubstNo(
//                                             '%1, %2 %3', DimText,
//                                             DimSetEntry2."Dimension Code", DimSetEntry2."Dimension Value Code");
//                                     if StrLen(DimText) > MaxStrLen(OldDimText) then begin
//                                         DimText := OldDimText;
//                                         Continue := true;
//                                         exit;
//                                     end;
//                                 until (DimSetEntry2.Next = 0);
//                                 //IN0090.BEGIN
//                                 if ShowInternalInfo then begin
//                                     NNC_SalesLineExciseAmt += SalesLine."Excise Amount";
//                                     NNC_SalesLineTaxAmt += SalesLine."Tax Amount";
//                                     NNC_SalesLineSvcTaxAmt += SalesLine."Service Tax Amount";
//                                     NNC_SalesLineSvcTaxeCessAmt += SalesLine."Service Tax eCess Amount";
//                                     NNC_SalesLineSvcSHECessAmt += SalesLine."Service Tax SHE Cess Amount";
//                                     NNC_SalesLineTDSTCSSHECESS += SalesLine."Total TDS/TCS Incl. SHE CESS";
//                                     NNC_SalesLineAmtToCustomer += SalesLine."Amount To Customer";
//                                     TotalAmount := NNC_SalesLineLineAmt - NNC_SalesLineInvDiscAmt + NNC_SalesLineExciseAmt + NNC_SalesLineTaxAmt
//                                      + NNC_SalesLineSvcTaxAmt + NNC_SalesLineSvcTaxeCessAmt + ChargesAmount +
//                                     OtherTaxesAmount
//                                      + NNC_SalesLineTDSTCSSHECESS + NNC_SalesLineSvcSHECessAmt;
//                                 end;
//                                 //IN0090.END
//                             end;

//                             trigger OnPostDataItem();
//                             begin
//                                 //IN0090.BEGIN
//                                 if not ShowInternalInfo then begin
//                                     NNC_SalesLineExciseAmt += SalesLine."Excise Amount";
//                                     NNC_SalesLineTaxAmt += SalesLine."Tax Amount";
//                                     NNC_SalesLineSvcTaxAmt += SalesLine."Service Tax Amount";
//                                     NNC_SalesLineSvcTaxeCessAmt += SalesLine."Service Tax eCess Amount";
//                                     NNC_SalesLineSvcSHECessAmt += SalesLine."Service Tax SHE Cess Amount";
//                                     NNC_SalesLineTDSTCSSHECESS += SalesLine."Total TDS/TCS Incl. SHE CESS";
//                                     NNC_SalesLineAmtToCustomer += SalesLine."Amount To Customer";
//                                     TotalAmount := NNC_SalesLineLineAmt - NNC_SalesLineInvDiscAmt + NNC_SalesLineExciseAmt + NNC_SalesLineTaxAmt
//                                      + NNC_SalesLineSvcTaxAmt + NNC_SalesLineSvcTaxeCessAmt + ChargesAmount +
//                                     OtherTaxesAmount
//                                      + NNC_SalesLineTDSTCSSHECESS + NNC_SalesLineSvcSHECessAmt;
//                                 end;
//                                 //IN0090.END
//                             end;

//                         }
//                         dataitem(AsmLoop; Integer)
//                         {
//                             DataItemTableView = sorting(Number);
//                             column(AsmLineUnitOfMeasureText; GetUnitOfMeasureDescr(AsmLine."Unit of Measure Code"))
//                             {
//                             }
//                             column(AsmLineQuantity; AsmLine.Quantity)
//                             {
//                             }
//                             column(AsmLineDescription; BlanksForIndent + AsmLine.Description)
//                             {
//                             }
//                             column(AsmLineNo; BlanksForIndent + AsmLine."No.")
//                             {
//                             }
//                             column(AsmLineType; AsmLine.Type)
//                             {
//                             }
//                             trigger OnPreDataItem();
//                             begin
//                                 if not DisplayAssemblyInformation then
//                                     CurrReport.Break;
//                                 if not AsmInfoExistsForLine then
//                                     CurrReport.Break;
//                                 AsmLine.SetRange("Document Type", AsmHeader."Document Type");
//                                 AsmLine.SetRange("Document No.", AsmHeader."No.");
//                                 SetRange(Number, 1, AsmLine.Count);
//                             end;

//                             trigger OnAfterGetRecord();
//                             begin
//                                 if Number = 1 then
//                                     AsmLine.FindSet
//                                 else
//                                     AsmLine.Next;
//                             end;

//                         }
//                         dataitem(SalesCommentLine; Integer)
//                         {
//                             column(Sales_Comment; SalesCommentLine1.Comment)
//                             {
//                             }
//                             column(Int; Int)
//                             {
//                             }
//                             trigger OnPreDataItem();
//                             begin
//                                 SalesCommentLine1.Reset;
//                                 SalesCommentLine1.SetRange("Document Type", SalesCommentLine1."document type"::Order);
//                                 SalesCommentLine1.SetRange("No.", "Sales Line"."Document No.");
//                                 SalesCommentLine1.SetRange("Document Line No.", "Sales Line"."Line No.");
//                                 Int := SalesCommentLine1.Count + 1;
//                                 SetRange(Number, 1, SalesCommentLine1.Count);
//                             end;

//                             trigger OnAfterGetRecord();
//                             begin
//                                 if Number = 1 then
//                                     SalesCommentLine1.FindSet
//                                 else
//                                     SalesCommentLine1.Next;
//                             end;

//                         }
//                         trigger OnPreDataItem();
//                         begin
//                             MoreLines := SalesLine.Find('+');
//                             while MoreLines and (SalesLine.Description = '') and (SalesLine."Description 2" = '') and
//                                   (SalesLine."No." = '') and (SalesLine.Quantity = 0) and
//                                   (SalesLine.Amount = 0)
//                             do
//                                 MoreLines := SalesLine.Next(-1) <> 0;
//                             if not MoreLines then
//                                 CurrReport.Break;
//                             SalesLine.SetRange("Line No.", 0, SalesLine."Line No.");
//                             SetRange(Number, 1, SalesLine.Count);

//                             //IN0090.BEGIN
//                             NNC_SalesLineExciseAmt := 0;
//                             NNC_SalesLineTaxAmt := 0;
//                             NNC_SalesLineSvcTaxAmt := 0;
//                             NNC_SalesLineSvcTaxeCessAmt := 0;
//                             NNC_SalesLineSvcSHECessAmt := 0;
//                             NNC_SalesLineTDSTCSSHECESS := 0;
//                             NNC_SalesLineAmtToCustomer := 0;
//                             //IN0090.END
//                         end;

//                         trigger OnAfterGetRecord();
//                         var
//                             // StructureLineDetails: Record "Structure Order Line Details";
//                             sl: Record "Sales Line";
//                         begin
//                             if Number = 1 then
//                                 SalesLine.Find('-')
//                             else
//                                 SalesLine.Next;
//                             "Sales Line" := SalesLine;
//                             if DisplayAssemblyInformation then
//                                 AsmInfoExistsForLine := SalesLine.AsmToOrderExists(AsmHeader);
//                             if not "Sales Header"."Prices Including VAT" and
//                                (SalesLine."VAT Calculation Type" = SalesLine."vat calculation type"::"Full VAT")
//                             then
//                                 SalesLine."Line Amount" := 0;
//                             if (SalesLine.Type = SalesLine.Type::"G/L Account") and (not ShowInternalInfo) then
//                                 "Sales Line"."No." := '';
//                             NNC_SalesLineLineAmt += SalesLine."Line Amount";
//                             NNC_SalesLineInvDiscAmt += SalesLine."Inv. Discount Amount";
//                             NNC_TotalLCY := NNC_SalesLineLineAmt - NNC_SalesLineInvDiscAmt;
//                             NNC_TotalExclVAT := NNC_TotalLCY;
//                             NNC_VATAmt := VATAmount;
//                             NNC_TotalInclVAT := NNC_TotalLCY - NNC_VATAmt;
//                             NNC_PmtDiscOnVAT := -VATDiscountAmount;
//                             NNC_TotalInclVAT2 := TotalAmountInclVAT;
//                             NNC_VatAmt2 := VATAmount;
//                             NNC_TotalExclVAT2 := VATBaseAmount;
//                             /*  StructureLineDetails.Reset;
//                              StructureLineDetails.SetRange(Type, StructureLineDetails.Type::Sale);
//                              StructureLineDetails.SetRange("Document Type", SalesLine."Document Type");
//                              StructureLineDetails.SetRange("Document No.", SalesLine."Document No.");
//                              StructureLineDetails.SetRange("Item No.", SalesLine."No.");
//                              StructureLineDetails.SetRange("Line No.", SalesLine."Line No.");
//                              if StructureLineDetails.Find('-') then
//                                  repeat
//                                      if not StructureLineDetails."Payable to Third Party" then begin
//                                          if StructureLineDetails."Tax/Charge Type" = StructureLineDetails."tax/charge type"::Charges then
//                                              ChargesAmount := ChargesAmount + ROUND(StructureLineDetails.Amount);
//                                          if StructureLineDetails."Tax/Charge Type" = StructureLineDetails."tax/charge type"::"Other Taxes" then
//                                              OtherTaxesAmount := OtherTaxesAmount + ROUND(StructureLineDetails.Amount);
//                                      end;
//                                  until StructureLineDetails.Next = 0; */ ////Lk (Structure Table missing )

//                             //IN0090.BEGIN
//                             //IN0090.END
//                             //akshya
//                             Serials := '';
//                             TempItemLedgerEntry.Reset;
//                             TempItemLedgerEntry.SetRange(TempItemLedgerEntry."Document Line No.", "Sales Line"."Line No.");
//                             if TempItemLedgerEntry.FindFirst then
//                                 Serials := TempItemLedgerEntry."Serial No.";
//                             CGSTAmt := 0;
//                             SGSTAmt := 0;
//                             IGSTAmt := 0;
//                             DedGSTEntryBuffer.Reset;
//                             DedGSTEntryBuffer.SetRange(DedGSTEntryBuffer."Document No.", "Sales Line"."Document No.");
//                             DedGSTEntryBuffer.SetRange(DedGSTEntryBuffer."Line No.", "Sales Line"."Line No.");
//                             DedGSTEntryBuffer.SetRange(DedGSTEntryBuffer."Document Type", DedGSTEntryBuffer."document type"::Order);
//                             DedGSTEntryBuffer.SetRange(DedGSTEntryBuffer."Source Type", DedGSTEntryBuffer."source type"::Customer);
//                             if DedGSTEntryBuffer.FindFirst then
//                                 repeat
//                                     if DedGSTEntryBuffer."GST Component Code" = 'CGST' then begin
//                                         CGSTRate := DedGSTEntryBuffer."GST %";
//                                         CGSTAmt := CGSTAmt + DedGSTEntryBuffer."GST Amount";
//                                     end;
//                                     // MESSAGE(FORMAT(CGSTAmt));
//                                     if DedGSTEntryBuffer."GST Component Code" = 'SGST' then begin
//                                         SGSTRate := DedGSTEntryBuffer."GST %";
//                                         SGSTAmt := SGSTAmt + DedGSTEntryBuffer."GST Amount";
//                                     end;
//                                     if DedGSTEntryBuffer."GST Component Code" = 'IGST' then begin
//                                         IGSTRate := DedGSTEntryBuffer."GST %";
//                                         IGSTAmt := IGSTAmt + DedGSTEntryBuffer."GST Amount";
//                                     end;
//                                 until DedGSTEntryBuffer.Next = 0;
//                             CGSTAmt := CGSTAmt * -1;
//                             SGSTAmt := SGSTAmt * -1;
//                             IGSTAmt := IGSTAmt * -1;
//                             TotalAmount := SalesLine."Line Amount" - VATAmountLine."Invoice Discount Amount" + SalesLine."Excise Amount" + SalesLine."Tax Amount"
//                               + SalesLine."Service Tax Amount" + SalesLine."Service Tax eCess Amount" + ChargesAmount + OtherTaxesAmount
//                               + SalesLine."Total TDS/TCS Incl. SHE CESS" + SalesLine."Service Tax SHE Cess Amount" + IGSTAmt + SGSTAmt + CGSTAmt;
//                             No_Int := 0;
//                             SCL.Reset;
//                             SCL.SetCurrentkey("Line No.");
//                             SCL.SetRange("Document Type", SCL."document type"::Order);
//                             SCL.SetRange("No.", SalesLine."Document No.");
//                             SCL.SetRange("Document Line No.", SalesLine."Line No.");
//                             if SCL.FindFirst then
//                                 No_Int := SCL.Count + 1
//                             else
//                                 No_Int := 2;
//                         end;

//                         trigger OnPostDataItem();
//                         begin
//                             SalesLine.DeleteAll;
//                         end;

//                     }
//                     dataitem(VATCounter; Integer)
//                     {
//                         DataItemTableView = sorting(Number);
//                         column(VATAmountLineVATBase; VATAmountLine."VAT Base")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(VATAmountLineVATAmount; VATAmountLine."VAT Amount")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(VATAmountLineLineAmount; VATAmountLine."Line Amount")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(VATAmtLineInvDiscBaseAmt; VATAmountLine."Inv. Disc. Base Amount")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(VATAmtLineInvDiscAmt; VATAmountLine."Invoice Discount Amount")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(VATAmountLineVAT; VATAmountLine."VAT %")
//                         {
//                             DecimalPlaces = 0 : 5;
//                         }
//                         column(VATAmtLineVATIdentifier; VATAmountLine."VAT Identifier")
//                         {
//                         }
//                         column(VATAmtSpecCaption; VATAmtSpecCaptionLbl)
//                         {
//                         }
//                         column(InvDiscBaseAmtCaption; InvDiscBaseAmtCaptionLbl)
//                         {
//                         }
//                         trigger OnPreDataItem();
//                         begin
//                             if VATAmount = 0 then
//                                 CurrReport.Break;
//                             SetRange(Number, 1, VATAmountLine.Count);

//                         end;

//                         trigger OnAfterGetRecord();
//                         begin
//                             VATAmountLine.GetLine(Number);
//                         end;

//                     }
//                     dataitem(VATCounterLCY; Integer)
//                     {
//                         DataItemTableView = sorting(Number);
//                         column(VALExchRate; VALExchRate)
//                         {
//                         }
//                         column(VALSpecLCYHeader; VALSpecLCYHeader)
//                         {
//                         }
//                         column(VALVATBaseLCY; VALVATBaseLCY)
//                         {
//                             AutoFormatType = 1;
//                         }
//                         column(VALVATAmountLCY; VALVATAmountLCY)
//                         {
//                             AutoFormatType = 1;
//                         }
//                         column(VATAmountLineVAT1; VATAmountLine."VAT %")
//                         {
//                             DecimalPlaces = 0 : 5;
//                         }
//                         column(VATAmtLineVATIdentifier1; VATAmountLine."VAT Identifier")
//                         {
//                         }
//                         trigger OnPreDataItem();
//                         begin
//                             if (not GLSetup."Print VAT specification in LCY") or
//                                ("Sales Header"."Currency Code" = '') or
//                                (VATAmountLine.GetTotalVATAmount = 0) then
//                                 CurrReport.Break;
//                             SetRange(Number, 1, VATAmountLine.Count);

//                             if GLSetup."LCY Code" = '' then
//                                 VALSpecLCYHeader := Text007 + Text008
//                             else
//                                 VALSpecLCYHeader := Text007 + Format(GLSetup."LCY Code");
//                             CurrExchRate.FindCurrency("Sales Header"."Posting Date", "Sales Header"."Currency Code", 1);
//                             VALExchRate := StrSubstNo(Text009, CurrExchRate."Relational Exch. Rate Amount", CurrExchRate."Exchange Rate Amount");
//                         end;

//                         trigger OnAfterGetRecord();
//                         begin
//                             VATAmountLine.GetLine(Number);
//                             VALVATBaseLCY := ROUND(CurrExchRate.ExchangeAmtFCYToLCY(
//                                                "Sales Header"."Posting Date", "Sales Header"."Currency Code",
//                                                VATAmountLine."VAT Base", "Sales Header"."Currency Factor"));
//                             VALVATAmountLCY := ROUND(CurrExchRate.ExchangeAmtFCYToLCY(
//                                                  "Sales Header"."Posting Date", "Sales Header"."Currency Code",
//                                                  VATAmountLine."VAT Amount", "Sales Header"."Currency Factor"));
//                         end;

//                     }
//                     dataitem(Total2; Integer)
//                     {
//                         DataItemTableView = sorting(Number) where(Number = const(1));
//                         column(SellToCustNo_SalesHeader; "Sales Header"."Sell-to Customer No.")
//                         {
//                             IncludeCaption = false;
//                         }
//                         column(ShipToAddr8; ShipToAddr[8])
//                         {
//                         }
//                         column(ShipToAddr7; ShipToAddr[7])
//                         {
//                         }
//                         column(ShipToAddr6; ShipToAddr[6])
//                         {
//                         }
//                         column(ShipToAddr5; ShipToAddr[5])
//                         {
//                         }
//                         column(ShipToAddr4; ShipToAddr[4])
//                         {
//                         }
//                         column(ShipToAddr3; ShipToAddr[3])
//                         {
//                         }
//                         column(ShipToAddr2; ShipToAddr[2])
//                         {
//                         }
//                         column(ShipToAddr1; ShipToAddr[1])
//                         {
//                         }
//                         column(ShipToAddrCaption; ShipToAddrCaptionLbl)
//                         {
//                         }
//                         column(SellToCustNo_SalesHeaderCaption; "Sales Header".FieldCaption("Sell-to Customer No."))
//                         {
//                         }
//                         trigger OnPreDataItem();
//                         begin
//                             if not ShowShippingAddr then
//                                 CurrReport.Break;
//                         end;

//                     }
//                     dataitem(PrepmtLoop; Integer)
//                     {
//                         DataItemTableView = sorting(Number) where(Number = filter(1 ..));
//                         column(PrepmtLineAmount; PrepmtLineAmount)
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(PrepmtInvBufDescription; PrepmtInvBuf.Description)
//                         {
//                         }
//                         column(PrepmtInvBufGLAccountNo; PrepmtInvBuf."G/L Account No.")
//                         {
//                         }
//                         column(TotalExclVATText1; TotalExclVATText)
//                         {
//                         }
//                         column(PrepmtVATAmtLineVATAmtText; PrepmtVATAmountLine.VATAmountText)
//                         {
//                         }
//                         column(TotalInclVATText1; TotalInclVATText)
//                         {
//                         }
//                         column(PrepmtInvBufAmount; PrepmtInvBuf.Amount)
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(PrepmtVATAmount; PrepmtVATAmount)
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(PrepmtInvBufAmtPrepmtVATAmt; PrepmtInvBuf.Amount + PrepmtVATAmount)
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(VATAmtLineVATAmtText1; VATAmountLine.VATAmountText)
//                         {
//                         }
//                         column(PrepmtTotalAmountInclVAT; PrepmtTotalAmountInclVAT)
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(PrepmtVATBaseAmount; PrepmtVATBaseAmount)
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(PmtTermsCaption; PmtTermsCaptionLbl)
//                         {
//                         }
//                         column(GLAccNoCaption; GLAccNoCaptionLbl)
//                         {
//                         }
//                         column(PrepmtSpecCaption; PrepmtSpecCaptionLbl)
//                         {
//                         }
//                         dataitem(PrepmtDimLoop; Integer)
//                         {
//                             DataItemTableView = sorting(Number) where(Number = filter(1 ..));
//                             column(ReportForNavId_6278; 6278) { } // Autogenerated by ForNav - Do not delete
//                             column(DimText2; DimText)
//                             {
//                             }
//                             trigger OnAfterGetRecord();
//                             begin
//                                 if Number = 1 then begin
//                                     if not PrepmtDimSetEntry.Find('-') then
//                                         CurrReport.Break;
//                                 end else
//                                     if not Continue then
//                                         CurrReport.Break;
//                                 Clear(DimText);
//                                 Continue := false;
//                                 repeat
//                                     OldDimText := DimText;
//                                     if DimText = '' then
//                                         DimText := StrSubstNo(
//                                           '%1 %2', PrepmtDimSetEntry."Dimension Code", PrepmtDimSetEntry."Dimension Value Code")
//                                     else
//                                         DimText :=
//                                           StrSubstNo(
//                                             '%1, %2 %3', DimText,
//                                             PrepmtDimSetEntry."Dimension Code", PrepmtDimSetEntry."Dimension Value Code");
//                                     if StrLen(DimText) > MaxStrLen(OldDimText) then begin
//                                         DimText := OldDimText;
//                                         Continue := true;
//                                         exit;
//                                     end;
//                                 until PrepmtDimSetEntry.Next = 0;
//                             end;

//                         }
//                         trigger OnPreDataItem();
//                         begin

//                         end;

//                         trigger OnAfterGetRecord();
//                         begin
//                             if Number = 1 then begin
//                                 if not PrepmtInvBuf.Find('-') then
//                                     CurrReport.Break;
//                             end else
//                                 if PrepmtInvBuf.Next = 0 then
//                                     CurrReport.Break;
//                             if ShowInternalInfo then
//                                 DimMgt.GetDimensionSet(PrepmtDimSetEntry, PrepmtInvBuf."Dimension Set ID");
//                             if "Sales Header"."Prices Including VAT" then
//                                 PrepmtLineAmount := PrepmtInvBuf."Amount Incl. VAT"
//                             else
//                                 PrepmtLineAmount := PrepmtInvBuf.Amount;
//                         end;

//                     }
//                     dataitem(PrepmtVATCounter; Integer)
//                     {
//                         DataItemTableView = sorting(Number);
//                         column(PrepmtVATAmtLineVATAmt; PrepmtVATAmountLine."VAT Amount")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(PrepmtVATAmtLineVATBase; PrepmtVATAmountLine."VAT Base")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(PrepmtVATAmtLineLineAmt; PrepmtVATAmountLine."Line Amount")
//                         {
//                             AutoFormatExpression = "Sales Header"."Currency Code";
//                             AutoFormatType = 1;
//                         }
//                         column(PrepmtVATAmountLineVAT; PrepmtVATAmountLine."VAT %")
//                         {
//                             DecimalPlaces = 0 : 5;
//                         }
//                         column(PrepmtVATAmtLineVATIdentifier; PrepmtVATAmountLine."VAT Identifier")
//                         {
//                         }
//                         column(PrepmtVATAmtSpecCaption; PrepmtVATAmtSpecCaptionLbl)
//                         {
//                         }
//                         trigger OnPreDataItem();
//                         begin
//                             SetRange(Number, 1, PrepmtVATAmountLine.Count);
//                         end;

//                         trigger OnAfterGetRecord();
//                         begin
//                             //PrepmtVATAmountLine.GetLine(Number);
//                         end;

//                     }
//                 }
//                 trigger OnPreDataItem();
//                 begin
//                     NoOfLoops := Abs(NoOfCopies) + 1;
//                     CopyText := '';
//                     SetRange(Number, 1, NoOfLoops);
//                     OutputNo := 1;
//                 end;

//                 trigger OnAfterGetRecord();
//                 var
//                     PrepmtSalesLine: Record "Sales Line" temporary;
//                     SalesPost: Codeunit "Sales-Post";
//                     TempSalesLine: Record "Sales Line" temporary;
//                     TempSalesLineDisc: Record "Sales Line" temporary;
//                 begin
//                     Clear(SalesLine);
//                     Clear(SalesPost);
//                     Clear(TempSalesLineDisc);
//                     VATAmountLine.DeleteAll;
//                     SalesLine.DeleteAll;
//                     TempSalesLineDisc.DeleteAll;
//                     SalesPost.GetSalesLines("Sales Header", SalesLine, 0);
//                     SalesLine.CalcVATAmountLines(0, "Sales Header", SalesLine, VATAmountLine);
//                     SalesLine.UpdateVATOnLines(0, "Sales Header", SalesLine, VATAmountLine);
//                     SalesPost.GetSalesLines("Sales Header", TempSalesLineDisc, 1);
//                     TempSalesLineDisc.CalcVATAmountLines(1, "Sales Header", TempSalesLineDisc, VATAmountLine);
//                     TempSalesLineDisc.UpdateVATOnLines(1, "Sales Header", TempSalesLineDisc, VATAmountLine);
//                     SalesLine."Inv. Discount Amount" := VATAmountLine."Invoice Discount Amount";
//                     VATAmount := VATAmountLine.GetTotalVATAmount;
//                     VATBaseAmount := VATAmountLine.GetTotalVATBase;
//                     VATDiscountAmount :=
//                       VATAmountLine.GetTotalVATDiscount("Sales Header"."Currency Code", "Sales Header"."Prices Including VAT");
//                     TotalAmountInclVAT := VATAmountLine.GetTotalAmountInclVAT;
//                     PrepmtInvBuf.DeleteAll;
//                     SalesPostPrepmt.GetSalesLines("Sales Header", 0, PrepmtSalesLine);
//                     if (not PrepmtSalesLine.IsEmpty) then begin
//                         SalesPostPrepmt.GetSalesLinesToDeduct("Sales Header", TempSalesLine);
//                         if not TempSalesLine.IsEmpty then
//                             SalesPostPrepmt.CalcVATAmountLines("Sales Header", TempSalesLine, PrepmtVATAmountLineDeduct, 1);
//                     end;
//                     SalesPostPrepmt.CalcVATAmountLines("Sales Header", PrepmtSalesLine, PrepmtVATAmountLine, 0);
//                     if PrepmtVATAmountLine.FindSet then
//                         repeat
//                             PrepmtVATAmountLineDeduct := PrepmtVATAmountLine;
//                             if PrepmtVATAmountLineDeduct.Find then begin
//                                 PrepmtVATAmountLine."VAT Base" := PrepmtVATAmountLine."VAT Base" - PrepmtVATAmountLineDeduct."VAT Base";
//                                 PrepmtVATAmountLine."VAT Amount" := PrepmtVATAmountLine."VAT Amount" - PrepmtVATAmountLineDeduct."VAT Amount";
//                                 PrepmtVATAmountLine."Amount Including VAT" := PrepmtVATAmountLine."Amount Including VAT" -
//                                   PrepmtVATAmountLineDeduct."Amount Including VAT";
//                                 PrepmtVATAmountLine."Line Amount" := PrepmtVATAmountLine."Line Amount" - PrepmtVATAmountLineDeduct."Line Amount";
//                                 PrepmtVATAmountLine."Inv. Disc. Base Amount" := PrepmtVATAmountLine."Inv. Disc. Base Amount" -
//                                   PrepmtVATAmountLineDeduct."Inv. Disc. Base Amount";
//                                 PrepmtVATAmountLine."Invoice Discount Amount" := PrepmtVATAmountLine."Invoice Discount Amount" -
//                                   PrepmtVATAmountLineDeduct."Invoice Discount Amount";
//                                 PrepmtVATAmountLine."Calculated VAT Amount" := PrepmtVATAmountLine."Calculated VAT Amount" -
//                                   PrepmtVATAmountLineDeduct."Calculated VAT Amount";
//                                 PrepmtVATAmountLine.Modify;
//                             end;
//                         until PrepmtVATAmountLine.Next = 0;
//                     SalesPostPrepmt.UpdateVATOnLines("Sales Header", PrepmtSalesLine, PrepmtVATAmountLine, 0);
//                     SalesPostPrepmt.BuildInvLineBuffer2("Sales Header", PrepmtSalesLine, 0, PrepmtInvBuf);
//                     PrepmtVATAmount := PrepmtVATAmountLine.GetTotalVATAmount;
//                     PrepmtVATBaseAmount := PrepmtVATAmountLine.GetTotalVATBase;
//                     PrepmtTotalAmountInclVAT := PrepmtVATAmountLine.GetTotalAmountInclVAT;
//                     if Number > 1 then begin
//                         CopyText := Text003;
//                         OutputNo += 1;
//                     end;

//                     NNC_TotalLCY := 0;
//                     NNC_TotalExclVAT := 0;
//                     NNC_VATAmt := 0;
//                     NNC_TotalInclVAT := 0;
//                     NNC_PmtDiscOnVAT := 0;
//                     NNC_TotalInclVAT2 := 0;
//                     NNC_VatAmt2 := 0;
//                     NNC_TotalExclVAT2 := 0;
//                     NNC_SalesLineLineAmt := 0;
//                     NNC_SalesLineInvDiscAmt := 0;
//                     ChargesAmount := 0;
//                     TotalAmount := 0;
//                     OtherTaxesAmount := 0;
//                 end;

//                 trigger OnPostDataItem();
//                 begin
//                     if Print then
//                         SalesCountPrinted.Run("Sales Header");
//                 end;

//             }
//             trigger OnPreDataItem();
//             var
//                 PBTPLTemrsCondition: Record "PBTPL Terms & Conditions";
//             begin
//                 //Print := Print OR NOT CurrReport.PREVIEW;
//                 AsmInfoExistsForLine := false;
//             end;

//             trigger OnAfterGetRecord();
//             begin
//                 //TandCInit.DELETEALL;
//                 ExtendedInformation := '';
//                 ExtensdedeInformation := '';
//                 ExtensdedeInformation := 'TDS NOTIFICATION';
//                 ExtSalesHeader.Reset;
//                 ExtSalesHeader.SetRange("Document No.", "Sales Header"."No.");
//                 ExtSalesHeader.SetRange(Type, ExtSalesHeader.Type::Item);
//                 if ExtSalesHeader.FindFirst then begin
//                     // IF ExtSalesHeader.Type=ExtSalesHeader.Type::Item THEN BEGIN
//                     ExtendedInformation := '"In terms of Notification No.21/2012 dated 13.06.2012, we hereby declare the item billed in this transaction vide Order No "' +
//                     "Sales Header"."No." + '" Dated "' + Format("Sales Header"."Posting Date") +
//                     '" is Software acquired in a subsequent transfer and is transferred without any modification and TDS had been already deducted by transferee vide PAN -"' +
//                     CompanyInfo."P.A.N. No." + '" under section 194J/Withholding Tax under section 195 of Income Tax On payment for any previous transfer of such software You are not required to deduct Tax at Source (TDS) on this Account."';
//                 end;
//                 // UNTIL ExtSalesHeader.NEXT=0;
//                 TandCInit1.Reset;
//                 TandCInit1.SetRange("Document No", "Sales Header"."No.");
//                 if not TandCInit1.FindFirst then begin
//                     TandCInit.Init;
//                     TandCInit."Document No" := "No.";
//                     TandCInit.Validate("Terms 1", Terrms1);
//                     TandCInit.Validate("Terms 2", Terrms2);
//                     TandCInit.Validate("Terms 3", Terrms3);
//                     TandCInit.Validate("Terms 4", Terrms4);
//                     TandCInit.Validate("Terms 5", Terrms5);
//                     TandCInit.Validate("Terms 6", '');
//                     TandCInit.Validate("Terms 7", '');
//                     TandCInit.Validate("Terms 8", '');
//                     TandCInit.Validate("Terms 9", '');
//                     TandCInit.Insert;
//                     Commit;
//                 end else begin
//                     Terrms1 := TandCInit1."Terms 1";
//                     Terrms2 := TandCInit1."Terms 2";
//                     Terrms3 := TandCInit1."Terms 3";
//                     Terrms4 := TandCInit1."Terms 4";
//                     Terrms5 := TandCInit1."Terms 5";
//                 end;
//                 CurrReport.Language := Language.GetLanguageID("Language Code");
//                 iprod := 1;
//                 Products.Reset;
//                 if Products.FindFirst then
//                     repeat
//                         Prod[iprod] := Products.Description;
//                         iprod += 1;
//                     until Products.Next = 0;
//                 if VarState.Get("Sales Header"."GST Bill-to State Code") then begin
//                     BilltoGSTRegNo := VarState."State Code (GST Reg. No.)";
//                 end;
//                 Cust.Reset;
//                 Cust.Get("Sales Header"."Bill-to Customer No.");
//                 BilltoGSTRegNo := Cust."GST Registration No.";
//                 //BilltoPANNo := Cust."P.A.N. No.";
//                 /*
// 				IF RespCenter.GET("Responsibility Center") THEN BEGIN
// 				  FormatAddr.RespCenter(CompanyAddr,RespCenter);
// 				  CompanyInfo."Phone No." := RespCenter."Phone No.";
// 				  CompanyInfo."Fax No." := RespCenter."Fax No.";
// 				END ELSE
// 				  FormatAddr.Company(CompanyAddr,CompanyInfo);
// 				 */
//                 if ShippingLocation.Get("Location Code") then begin
//                     //FormatAddr.Location(CompanyAddr,ShippingLocation);//alp
//                     CompanyAddr[1] := CompanyInfo.Name;
//                 end else
//                     FormatAddr.Company(CompanyAddr, CompanyInfo);
//                 DimSetEntry1.SetRange("Dimension Set ID", "Sales Header"."Dimension Set ID");
//                 if "Salesperson Code" = '' then begin
//                     Clear(SalesPurchPerson);
//                     SalesPersonText := '';
//                 end else begin
//                     SalesPurchPerson.Get("Salesperson Code");
//                     SalesPersonText := Text000;
//                 end;
//                 if "Your Reference" = '' then
//                     ReferenceText := ''
//                 else
//                     ReferenceText := FieldCaption("Your Reference");
//                 //IF Cust."GST Registration No." = '' THEN
//                 //VATNoText := ''
//                 //ELSE
//                 //VATNoText := FIELDCAPTION(Cust."GST Registration No.");
//                 CurrText := '';
//                 if "Currency Code" = '' then begin
//                     GLSetup.TestField("LCY Code");
//                     TotalText := StrSubstNo(Text001, GLSetup."LCY Code");
//                     TotalInclVATText := StrSubstNo(Text13700, GLSetup."LCY Code");
//                     TotalExclVATText := StrSubstNo(Text13701, GLSetup."LCY Code");
//                 end else begin
//                     Clear(Currency);
//                     Currency.SetRange(Code, "Currency Code");
//                     if Currency.FindFirst then
//                         CurrText := Currency.Description;
//                     TotalText := StrSubstNo(Text001, CurrText);
//                     TotalInclVATText := StrSubstNo(Text13700, CurrText);
//                     TotalExclVATText := StrSubstNo(Text13701, CurrText);
//                 end;
//                 FormatAddr.SalesHeaderBillTo(CustAddr, "Sales Header");
//                 if "Payment Terms Code" = '' then
//                     PaymentTerms.Init
//                 else begin
//                     PaymentTerms.Get("Payment Terms Code");
//                     PaymentTerms.TranslateDescription(PaymentTerms, "Sales Header"."Language Code");
//                 end;
//                 if "Prepmt. Payment Terms Code" = '' then
//                     PrepmtPaymentTerms.Init
//                 else begin
//                     PrepmtPaymentTerms.Get("Prepmt. Payment Terms Code");
//                     PrepmtPaymentTerms.TranslateDescription(PrepmtPaymentTerms, "Sales Header"."Language Code");
//                 end;
//                 if "Prepmt. Payment Terms Code" = '' then
//                     PrepmtPaymentTerms.Init
//                 else begin
//                     PrepmtPaymentTerms.Get("Prepmt. Payment Terms Code");
//                     PrepmtPaymentTerms.TranslateDescription(PrepmtPaymentTerms, "Sales Header"."Language Code");
//                 end;
//                 if "Shipment Method Code" = '' then
//                     ShipmentMethod.Init
//                 else begin
//                     ShipmentMethod.Get("Shipment Method Code");
//                     ShipmentMethod.TranslateDescription(ShipmentMethod, "Sales Header"."Language Code");
//                 end;
//                 FormatAddr.SalesHeaderShipTo(ShipToAddr, CustAddr, "Sales Header");
//                 ShowShippingAddr := "Sell-to Customer No." <> "Bill-to Customer No.";
//                 for i := 1 to ArrayLen(ShipToAddr) do
//                     if ShipToAddr[i] <> CustAddr[i] then
//                         ShowShippingAddr := true;
//                 if Print then begin
//                     if ArchiveDocument then
//                         ArchiveManagement.StoreSalesDocument("Sales Header", LogInteraction);
//                     if LogInteraction then begin
//                         CalcFields("No. of Archived Versions");
//                         if "Bill-to Contact No." <> '' then
//                             SegManagement.LogDocument(
//                               3, "No.", "Doc. No. Occurrence",
//                               "No. of Archived Versions", Database::Contact, "Bill-to Contact No."
//                               , "Salesperson Code", "Campaign No.", "Posting Description", "Opportunity No.")
//                         else
//                             SegManagement.LogDocument(
//                               3, "No.", "Doc. No. Occurrence",
//                               "No. of Archived Versions", Database::Customer, "Bill-to Customer No.",
//                               "Salesperson Code", "Campaign No.", "Posting Description", "Opportunity No.");
//                     end;
//                 end;
//                 //akshya
//                 location.Reset;
//                 location.SetRange(location.Code, "Sales Header"."Location Code");
//                 if location.FindFirst then
//                     locationTIN := 'TIN No.' + location."T.I.N. No.";
//                 LocationServiceTax := 'GST Reg NO' + location."GST Registration No.";
//                 SbCessAmt := 0;
//             /*     StrOrdLineDet.Reset;
//                 StrOrdLineDet.SetRange(StrOrdLineDet."Document No.", "No.");
//                 StrOrdLineDet.SetFilter(StrOrdLineDet."Tax/Charge Code", '%1|%2', 'SB', 'SBCESS');
//                 if StrOrdLineDet.FindFirst then
//                     repeat
//                         SBCessPerc := StrOrdLineDet."Calculation Value";
//                         SbCessAmt += StrOrdLineDet.Amount;
//                     until StrOrdLineDet.Next = 0;
//                 kkCAmt := 0;
//                 StrOrdLineDet.Reset;
//                 StrOrdLineDet.SetRange(StrOrdLineDet."Document No.", "No.");
//                 StrOrdLineDet.SetFilter(StrOrdLineDet."Tax/Charge Code", '%1', 'KKCess');
//                 if StrOrdLineDet.FindFirst then
//                     repeat
//                         //SBCessPerc := StrOrdLineDet."Calculation Value";
//                         kkCAmt += StrOrdLineDet.Amount;
//                     until StrOrdLineDet.Next = 0;
//                 StrOrdLineDet.Reset;
//                 ServiceTaxAmount := 0;
//                 StrOrdLineDet.SetRange(StrOrdLineDet."Document No.", "No.");
//                 StrOrdLineDet.SetRange(StrOrdLineDet."Tax/Charge Type", StrOrdLineDet."tax/charge type"::"Service Tax");
//                 if StrOrdLineDet.FindFirst then
//                     repeat
//                         ServiceTaxAmount += StrOrdLineDet.Amount;
//                     until StrOrdLineDet.Next = 0; */ //Lk (Structure Table missing )

//             end;

//         }
//     }

//     requestpage
//     {

//         SaveValues = true;

//         layout
//         {
//             area(content)
//             {
//                 group(Options)
//                 {
//                     Caption = 'Options';
//                     field(NoOfCopies; NoOfCopies)
//                     {
//                         ApplicationArea = Basic;
//                         Caption = 'No. of Copies';
//                     }
//                     field("Show Terms"; ShowTerms)
//                     {
//                         ApplicationArea = Basic;
//                     }
//                     field(ShowInternalInfo; ShowInternalInfo)
//                     {
//                         ApplicationArea = Basic;
//                         Caption = 'Show Internal Information';
//                     }
//                     field(ArchiveDocument; ArchiveDocument)
//                     {
//                         ApplicationArea = Basic;
//                         Caption = 'Archive Document';

//                         trigger OnValidate()
//                         begin
//                             if not ArchiveDocument then
//                                 LogInteraction := false;
//                         end;
//                     }
//                     field(LogInteraction; LogInteraction)
//                     {
//                         ApplicationArea = Basic;
//                         Caption = 'Log Interaction';
//                         Enabled = LogInteractionEnable;

//                         trigger OnValidate()
//                         begin
//                             if LogInteraction then
//                                 ArchiveDocument := ArchiveDocumentEnable;
//                         end;
//                     }
//                     field(ShowAssemblyComponents; DisplayAssemblyInformation)
//                     {
//                         ApplicationArea = Basic;
//                         Caption = 'Show Assembly Components';
//                     }
//                     field("Print Product"; ProductBoolean)
//                     {
//                         ApplicationArea = Basic;
//                     }
//                     field("Logo Ax"; Logo_Ax_P)
//                     {
//                         ApplicationArea = Basic;
//                     }
//                     field("Print Terms"; PRint_Terms)
//                     {
//                         ApplicationArea = Basic;
//                     }
//                     field("Terrms 1"; Terrms1)
//                     {
//                         ApplicationArea = Basic;
//                     }
//                     field("Terrms 2"; Terrms2)
//                     {
//                         ApplicationArea = Basic;
//                     }
//                     field("Terrms 3"; Terrms3)
//                     {
//                         ApplicationArea = Basic;
//                     }
//                     field("Terrms 4"; Terrms4)
//                     {
//                         ApplicationArea = Basic;
//                     }
//                     field("Terrms 5"; Terrms5)
//                     {
//                         ApplicationArea = Basic;
//                     }

//                 }
//             }
//         }

//         actions
//         {
//         }

//         trigger OnInit()
//         begin
//             LogInteractionEnable := true;
//         end;

//         trigger OnOpenPage()
//         begin
//             ArchiveDocument := SalesSetup."Archive Quotes and Orders";
//             LogInteraction := SegManagement.FindInteractTmplCode(3) <> '';
//             LogInteractionEnable := LogInteraction;
//             ProductBoolean := false;
//         end;
//     }

//     trigger OnInitReport()
//     var
//         PBTPLTemrsCondition: Record "PBTPL Terms & Conditions";
//     begin
//         GLSetup.Get;
//         CompanyInfo.Get;
//         PRint_Terms := true;
//         /*
// 		PBTPLTemrsCondition.RESET;
// 		PBTPLTemrsCondition.SETRANGE("Document No","Sales Header"."No.");
// 		IF PBTPLTemrsCondition.FINDFIRST THEN BEGIN
// 		  Terrms1 := PBTPLTemrsCondition."Terms 1";
// 		Terrms2 := PBTPLTemrsCondition."Terms 2";
// 		Terrms3 := PBTPLTemrsCondition."Terms 3";
// 		Terrms4 := PBTPLTemrsCondition."Terms 4";
// 		Terrms5 := PBTPLTemrsCondition."Terms 5";
// 		END ELSE BEGIN
// 		SalesSetup.GET;
// 		Terrms1 := SalesSetup."Terms 1";
// 		Terrms2 := SalesSetup."Terms 2";
// 		Terrms3 := SalesSetup."Terms 3";
// 		Terrms4 := SalesSetup."Terms 4";
// 		Terrms5 := SalesSetup."Terms 5";
// 		END;
// 		*/
//         case SalesSetup."Logo Position on Documents" of
//             SalesSetup."logo position on documents"::"No Logo":
//                 ;
//             SalesSetup."logo position on documents"::Left:
//                 begin
//                     CompanyInfo3.Get;
//                     CompanyInfo3.CalcFields(Picture);
//                 end;
//             SalesSetup."logo position on documents"::Center:
//                 begin
//                     CompanyInfo1.Get;
//                     CompanyInfo1.CalcFields(Picture);
//                 end;
//             SalesSetup."logo position on documents"::Right:
//                 begin
//                     CompanyInfo2.Get;
//                     CompanyInfo2.CalcFields(Picture);
//                 end;
//         end;


//     end;



//     trigger OnPreReport()
//     begin
//         if Logo_Ax_P then
//             CompanyInfo.CalcFields("Logo AX")
//         else
//             CompanyInfo.CalcFields("Logo NAV");

//     end;

//     var
//         Text000: label 'Salesperson';
//         Text001: label 'Total %1';
//         Text002: label 'Total %1 Incl. VAT';
//         Text003: label ' COPY';
//         Text004: label 'Order Confirmation%1';
//         Text005: label 'Page %1';
//         Text006: label 'Total %1 Excl. VAT';
//         GLSetup: Record "General Ledger Setup";
//         ShipmentMethod: Record "Shipment Method";
//         PaymentTerms: Record "Payment Terms";
//         PrepmtPaymentTerms: Record "Payment Terms";
//         SalesPurchPerson: Record "Salesperson/Purchaser";
//         CompanyInfo: Record "Company Information";
//         CompanyInfo1: Record "Company Information";
//         CompanyInfo2: Record "Company Information";
//         CompanyInfo3: Record "Company Information";
//         SalesSetup: Record "Sales & Receivables Setup";
//         VATAmountLine: Record "VAT Amount Line" temporary;
//         PrepmtVATAmountLine: Record "VAT Amount Line" temporary;
//         PrepmtVATAmountLineDeduct: Record "VAT Amount Line" temporary;
//         SalesLine: Record "Sales Line" temporary;
//         DimSetEntry1: Record "Dimension Set Entry";
//         DimSetEntry2: Record "Dimension Set Entry";
//         PrepmtDimSetEntry: Record "Dimension Set Entry" temporary;
//         PrepmtInvBuf: Record "Prepayment Inv. Line Buffer" temporary;
//         RespCenter: Record "MICR Codes";
//         Language: Record Language;
//         CurrExchRate: Record "Currency Exchange Rate";
//         AsmHeader: Record "Assembly Header";
//         AsmLine: Record "Assembly Line";
//         SalesCountPrinted: Codeunit "Sales-Printed";
//         FormatAddr: Codeunit "Format Address";
//         SegManagement: Codeunit SegManagement;
//         ArchiveManagement: Codeunit ArchiveManagement;
//         SalesPostPrepmt: Codeunit "Sales-Post Prepayments";
//         DimMgt: Codeunit DimensionManagement;
//         CustAddr: array[8] of Text[50];
//         ShipToAddr: array[8] of Text[50];
//         CompanyAddr: array[8] of Text[50];
//         SalesPersonText: Text[30];
//         VATNoText: Text[80];
//         ReferenceText: Text[80];
//         TotalText: Text[50];
//         TotalExclVATText: Text[50];
//         TotalInclVATText: Text[50];
//         MoreLines: Boolean;
//         NoOfCopies: Integer;
//         NoOfLoops: Integer;
//         CopyText: Text[30];
//         ShowShippingAddr: Boolean;
//         i: Integer;
//         DimText: Text[120];
//         OldDimText: Text[75];
//         ShowInternalInfo: Boolean;
//         Continue: Boolean;
//         ArchiveDocument: Boolean;
//         LogInteraction: Boolean;
//         VATAmount: Decimal;
//         VATBaseAmount: Decimal;
//         VATDiscountAmount: Decimal;
//         TotalAmountInclVAT: Decimal;
//         VALVATBaseLCY: Decimal;
//         VALVATAmountLCY: Decimal;
//         VALSpecLCYHeader: Text[80];
//         Text007: label 'VAT Amount Specification in ';
//         Text008: label 'Local Currency';
//         Text009: label 'Exchange rate: %1/%2';
//         VALExchRate: Text[50];
//         PrepmtVATAmount: Decimal;
//         PrepmtVATBaseAmount: Decimal;
//         PrepmtAmountInclVAT: Decimal;
//         PrepmtTotalAmountInclVAT: Decimal;
//         PrepmtLineAmount: Decimal;
//         OutputNo: Integer;
//         NNC_TotalLCY: Decimal;
//         NNC_TotalExclVAT: Decimal;
//         NNC_VATAmt: Decimal;
//         NNC_TotalInclVAT: Decimal;
//         NNC_PmtDiscOnVAT: Decimal;
//         NNC_TotalInclVAT2: Decimal;
//         NNC_VatAmt2: Decimal;
//         NNC_TotalExclVAT2: Decimal;
//         NNC_SalesLineLineAmt: Decimal;
//         NNC_SalesLineInvDiscAmt: Decimal;
//         Print: Boolean;
//         ChargesAmount: Decimal;
//         OtherTaxesAmount: Decimal;
//         Text13700: label 'Total %1 Incl. Taxes';
//         Text13701: label 'Total %1 Excl. Taxes';
//         TotalAmount: Decimal;
//         NNC_SalesLineSvcTaxeCessAmt: Decimal;
//         NNC_SalesLineExciseAmt: Decimal;
//         NNC_SalesLineTaxAmt: Decimal;
//         NNC_SalesLineSvcTaxAmt: Decimal;
//         NNC_SalesLineSvcSHECessAmt: Decimal;
//         NNC_SalesLineTDSTCSSHECESS: Decimal;
//         NNC_SalesLineAmtToCustomer: Decimal;
//         [InDataSet]
//         ArchiveDocumentEnable: Boolean;
//         [InDataSet]
//         LogInteractionEnable: Boolean;
//         DisplayAssemblyInformation: Boolean;
//         AsmInfoExistsForLine: Boolean;
//         PhoneNoCaptionLbl: label 'Phone No.';
//         HomePageCaptionLbl: label 'Home Page';
//         VATRegNoCaptionLbl: label 'GST Registration No.';
//         GiroNoCaptionLbl: label 'Giro No.';
//         BankNameCaptionLbl: label 'Bank';
//         BankAccNoCaptionLbl: label 'Customer PO No.';
//         ShpDateCaptionLbl: label 'Shipment Date';
//         OrderNoCaptionLbl: label 'Order No.';
//         EMailCaptionLbl: label 'E-Mail';
//         PmtTermsDescCaptionLbl: label 'Payment Terms';
//         ShipMethodDescCaptionLbl: label 'Shipment Method';
//         PrepmtTermsDescCaptionLbl: label 'Prepayment Payment Terms';
//         DocDateCaptionLbl: label 'Document Date';
//         AmtCaptionLbl: label 'Amount';
//         HdrDimsCaptionLbl: label 'Header Dimensions';
//         UnitPriceCaptionLbl: label 'Unit Price';
//         DiscPercentCaptionLbl: label 'Discount %';
//         LineDiscCaptionLbl: label 'Discount Value';
//         SubtotalCaptionLbl: label 'Subtotal';
//         ExciseAmtCaptionLbl: label 'Excise Amount';
//         TaxAmtCaptionLbl: label 'Tax Amount';
//         ServTaxAmtCaptionLbl: label 'Service Tax Amount';
//         ChargesAmtCaptionLbl: label 'Charges Amount';
//         OtherTaxesAmtCaptionLbl: label 'Other Taxes Amount';
//         ServTaxeCessAmtCaptionLbl: label 'Service Tax eCess Amount';
//         TCSAmtCaptionLbl: label 'TCS Amount';
//         ServTaxSHECessAmtCaptionLbl: label 'Service Tax SHECess Amount';
//         VATDisctAmtCaptionLbl: label 'Payment Discount on VAT';
//         LineDimsCaptionLbl: label 'Line Dimensions';
//         VATAmtSpecCaptionLbl: label 'VAT Amount Specification';
//         InvDiscBaseAmtCaptionLbl: label 'Invoice Discount Base Amount';
//         ShipToAddrCaptionLbl: label 'Ship-to Address';
//         PmtTermsCaptionLbl: label 'Description';
//         GLAccNoCaptionLbl: label 'G/L Account No.';
//         PrepmtSpecCaptionLbl: label 'Prepayment Specification';
//         PrepmtVATAmtSpecCaptionLbl: label 'Prepayment VAT Amount Specification';
//         InvDiscAmtCaptionLbl: label 'Invoice Discount Amount';
//         VATPercentCaptionLbl: label 'VAT %';
//         VATBaseCaptionLbl: label 'VAT Base';
//         VATAmtCaptionLbl: label 'VAT Amount';
//         LineAmtCaptionLbl: label 'Line Amount';
//         VATIdentCaptionLbl: label 'VAT Identifier';
//         TotalCaptionLbl: label 'Total';
//         ShippingLocation: Record Location;
//         location: Record Location;
//         locationTIN: Text[100];
//         LocationServiceTax: Text[100];
//         TempItemLedgerEntry: Record "Item Ledger Entry";
//         Serials: Text[100];
//         Products: Record "Product Group";
//         Prod: array[20] of Text;
//         iprod: Integer;
//         ShowTerms: Boolean;
//         // StrOrdLineDet: Record "Structure Order Line Details";
//         SBCess: Decimal;
//         SBCessPerc: Decimal;
//         SbCessAmt: Decimal;
//         ServiceTaxAmount: Decimal;
//         kkCAmt: Decimal;
//         CGSTAmt: Decimal;
//         SGSTAmt: Decimal;
//         IGSTAmt: Decimal;
//         CGSTRate: Decimal;
//         SGSTRate: Decimal;
//         IGSTRate: Decimal;
//         DedGSTEntryBuffer: Record "Detailed GST Entry Buffer";
//         BilltoGSTRegNo: Text;
//         VarState: Record State;
//         BilltoPANNo: Text;
//         Cust: Record Customer;
//         ProductBoolean: Boolean;
//         SalesRece_rec: Record "Sales & Receivables Setup";
//         Logo_Ax_P: Boolean;
//         Comment_text: array[25] of Text;
//         No_Int: Integer;
//         Int: Integer;
//         SalesCommentLine1: Record "Sales Comment Line";
//         SCL: Record "Sales Comment Line";
//         contect_person: Text;
//         contectmailid: Text;
//         Terrms1: Text;
//         Terrms2: Text;
//         Terrms3: Text;
//         Terrms4: Text;
//         Terrms5: Text;
//         PRint_Terms: Boolean;
//         SendMAiL: Boolean;
//         SendtoDK: Boolean;
//         SendtoCustoMer: Boolean;
//         FileName: Text;
//         OutStr: OutStream;
//         rEcrEF: RecordRef;
//         TandCInit: Record "PBTPL Terms & Conditions";
//         TandCInit1: Record "PBTPL Terms & Conditions";
//         Currency: Record Currency;
//         CurrText: Text;
//         ExtendedInformation: Text;
//         ExtensdedeInformation: Text;
//         ExtSalesHeader: Record "Sales Line";

//     procedure InitializeRequest(NoOfCopiesFrom: Integer; ShowInternalInfoFrom: Boolean; ArchiveDocumentFrom: Boolean; LogInteractionFrom: Boolean; PrintFrom: Boolean; DisplAsmInfo: Boolean)
//     begin
//         NoOfCopies := NoOfCopiesFrom;
//         ShowInternalInfo := ShowInternalInfoFrom;
//         ArchiveDocument := ArchiveDocumentFrom;
//         LogInteraction := LogInteractionFrom;
//         Print := PrintFrom;
//         DisplayAssemblyInformation := DisplAsmInfo;
//     end;

//     procedure GetUnitOfMeasureDescr(UOMCode: Code[10]): Text[10]
//     var
//         UnitOfMeasure: Record "Unit of Measure";
//     begin
//         if not UnitOfMeasure.Get(UOMCode) then
//             exit(UOMCode);
//         exit(UnitOfMeasure.Description);
//     end;

//     procedure BlanksForIndent(): Text[10]
//     begin
//         exit(PadStr('', 2, ' '));
//     end;


// }
